In [1]:
pip install numpy

In [1]:
import numpy as np

In [3]:
my_first_array = np.array([1,2,3,4,5,6,7])

In [4]:
print(my_first_array)

[1 2 3 4 5 6 7]


In [12]:
type(my_first_array)

numpy.ndarray

In [11]:
print(np.__version__)

1.20.3


In [13]:
arr = np.array((1,2,3,4,5,6,7))

In [14]:
print(arr)

[1 2 3 4 5 6 7]


In [15]:
type(arr)

numpy.ndarray

In [16]:
arr = np.array(20)

In [18]:
print(type(arr))

<class 'numpy.ndarray'>


In [19]:
print(arr)

20


In [20]:
# 0-D arrays

zi = np.array(40)

print(zi)

40


In [21]:
# 1-D array

one_direct = np.array([1,2,3,4,5,6,7])

print(one_direct)

[1 2 3 4 5 6 7]


In [27]:
# 2-D array is an array that has 1-D arrays as its elements

arr = np.array([[1,2,3,4], [5,6,7,8]])

print(arr)

[[1 2 3 4]
 [5 6 7 8]]


In [35]:
# 3-D arrays. An array that has 2-D arrays(matrices) as its elements is called 3-D array

arr = np.array([[[1,2,3], [4,5,6]], [[1,2,3], [4,5,6]]])

In [36]:
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [37]:
# find out how many dimensions an array has

arr.ndim

3

In [38]:
print(arr.ndim)

3


In [40]:
arr = np.array([1,2,3,4,5], ndmin=4)

In [41]:
print(arr)

[[[[1 2 3 4 5]]]]


In [44]:
print(arr.ndim)

4


In [53]:
print('this array has' " " + str(arr.ndim) + " " 'dimensions')

this array has 4 dimensions


# Array Indexing or How to Access Array Elements

You can access an array elements by using its index. Numpy array indexes start from index 0.

In [54]:
arr = np.array([1,2,3,4,5,6,7])

print(arr[0])

1


In [56]:
print(arr[5])

6


In [57]:
print(arr[4] + arr[3])

9


In [58]:
# to access 2-D arrays use two comma separated values, these values represent the dimension and the index of the element you want.

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st dim:', arr[0,1])

2nd element on 1st dim: 2


In [60]:
print('3rd element on 2nd dimension:', arr[1, 3])

3rd element on 2nd dimension: 9


# Numpy Array Slicing

Slicing means taking elements from one given index to another given index.

You can slice using : [start:end] and [start;end:step]

In [61]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])

print(arr[3:9])

[4 5 6 7 8 9]


In [64]:
print(arr[1:9:3])

[2 5 8]


In [65]:
print(arr[4:])

[ 5  6  7  8  9 10]


In [67]:
print(arr[:6])

[1 2 3 4 5 6]


In [68]:
# Negative slicing

print(arr[:-1])

[1 2 3 4 5 6 7 8 9]


In [84]:
arr = np.array([0, 0, 0, 0], ndmin=2)

In [85]:
print(arr)

[[0 0 0 0]]


In [86]:
arr.ndim

2

In [89]:
# creating an array filled with zeros
np.zeros(4)

array([0., 0., 0., 0.])

In [88]:
# creating an array filled with ones

np.ones(4)

array([1., 1., 1., 1.])

In [92]:
np.empty(2)

array([0., 0.])

In [93]:
# create an array with a range of elements
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [95]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

# Adding, Removing and Sorting Array Elements.

You use np.sort() and np.concatenate() functions

When sorting with np.sort(), you can specify the axis, kind, and order when using the function.




In [96]:
arr = np.arange(10)

In [97]:
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [98]:
type(arr)

numpy.ndarray

In [104]:
arr = np.array([10, 9, 12, 15, 30, 54, 3, 8, 9, 11])

In [106]:
print(arr)

[10  9 12 15 30 54  3  8  9 11]


In [108]:
print(np.sort(arr))

[ 3  8  9  9 10 11 12 15 30 54]


In [109]:
# Concatenate two arrays

a = np.array([1, 2, 3, 4])

b = np.array([5, 6, 7, 8,])


In [112]:
c = np.concatenate((a, b))

In [113]:
print(c)

[1 2 3 4 5 6 7 8]


In [114]:
# Another example

x = np.array([[1,2], [3,4]])

y = np.array([[5, 6]])


In [115]:
z = np.concatenate((x,y), axis=0)

In [116]:
print(z)

[[1 2]
 [3 4]
 [5 6]]


In [117]:
#ndarray.ndim used to tell the number of dimensions or axes of an array

z.ndim

2

In [119]:
#ndarray.size used to find the total number of elements of an array

z.size

6

In [121]:
# ndarray.shape, used to display a tuple of numbers that show the number of elements stored along each dimension of the array
# it shows that the array z has 3 rows and 2 columns

print(z)
z.shape

[[1 2]
 [3 4]
 [5 6]]


(3, 2)

In [122]:
# Reshaping an array with arr.reshape()

p = np.arange(10)

In [123]:
print(p)

[0 1 2 3 4 5 6 7 8 9]


In [125]:
# reshaping the array

r = p.reshape(5,2)

In [126]:
print(r)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [127]:
q = p.reshape(2, 5)

In [128]:
print(q)

[[0 1 2 3 4]
 [5 6 7 8 9]]


# Filtering through arrays in Numpy using for loop

In [138]:
arr = np.array([2, 11, 23, 24, 34, 45, 43, 47, 6, 5, 48, 7, 87, 9, 60, 100, 50])
filtered_arr = []

for i in arr:
    if i < 30:
        filtered_arr.append(True)
    else:
        filtered_arr.append(False)
        
new_arr = arr[filtered_arr]

In [139]:
print(filtered_arr)

[True, True, True, True, False, False, False, False, True, True, False, True, False, True, False, False, False]


In [140]:
print(new_arr)

[ 2 11 23 24  6  5  7  9]


# Create Filter Directly from Array

In [141]:
# instead of using the for loop to filter we can filter directly using comparison operators

print(arr)

[  2  11  23  24  34  45  43  47   6   5  48   7  87   9  60 100  50]


In [145]:
filter_arr = arr < 30

new_arr = arr[filter_arr]

In [146]:
print(filter_arr)

[ True  True  True  True False False False False  True  True False  True
 False  True False False False]


In [147]:
print(new_arr)

[ 2 11 23 24  6  5  7  9]


In [149]:
# create a filter that returns only even numbers from the arr

filter_arr = arr % 2 == 0

new_arr = arr[filter_arr]

print(filter_arr)

print(new_arr)

[ True False False  True  True False False False  True False  True False
 False False  True  True  True]
[  2  24  34   6  48  60 100  50]


In [150]:
# create a filter that returns only odd numbers from the arr

filter_arr = arr % 2 != 0

new_arr = arr[filter_arr]

print(filter_arr)

print(new_arr)

[False  True  True False False  True  True  True False  True False  True
  True  True False False False]
[11 23 45 43 47  5  7 87  9]
